### ISSUE TITLE
dn' is not in list

### ISSUE THREAD

**Issue by EnricoSx** [openemail/csv2ldif2csv#1]
csv2ldif2csv$ ./csv2ldif aziende.csv > aziende.ldif
Traceback (most recent call last):
  File "./csv2ldif", line 190, in <module>
    main()
  File "./csv2ldif", line 40, in main
    dn_index = attrs.index('dn')
ValueError: 'dn' is not in list

**Comment by larok972** [comment]
Hi EnricoSx

1- Try this syntax in your filename.csv file for example:

"dn";"email";"objectclass";
"uid=johndoe,dc=example,dc=com";"johndoe@example.com";"inetOrgPerson|top";"";

2- Launch python3 csv2ldif.py filename.csv > filename.ldif or ./csv2ldif.py filename.csv > filename.ldif and it works!

Kindest
